### ISSUE TITLE
Wild Place and parish outlines

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#127]
Currently we use coloured shading to mark the outlines of both Wild Places and a selected parish on the parish pages. Feedback has pointed to this obscuring detail on the maps that would be helpful to view more clearly. Could we remove the shading and instead use a coloured boundary line? If this is a minor job (<1hr) then just do it please!
Would it be easy to remove the orange shading of the selected square on the submit records form and replace it with a coloured outline, for similar reasons?

**Comment by johnvanbreda** [comment]
Both changes done.

**Comment by davidnicholls125** [comment]
Thanks John. The Wild Places are still displaying with a red fill (on Wild Places pages, Parish pages and on the Wild Place VC55 map). Is this just a caching delay?

**Comment by johnvanbreda** [comment]
Caching on the main wild place/parish page, but on the wild places page I'd not actually changed anything - I've now done that page as well and cleared the cache.

**Comment by davidnicholls125** [comment]
Thanks. Could we make the selected Wild Place boundary pink so there isn’t a confusion with the VC55 boundary? Or a bolder red boundary perhaps (I can change the key below the map as needed).

**Comment by johnvanbreda** [comment]
Done - I've used an orange colour which seemed to work.

**Comment by davidnicholls125** [comment]
Great, thanks.

**Comment by davidnicholls125** [comment]
Just noticed, those on the Wild Places map page still have the red fill…..

**Comment by johnvanbreda** [comment]
Do you mean https://www.naturespot.org.uk/wild_places? They aren't filed for me.

**Comment by davidnicholls125** [comment]
Ah, it was my browser cache, sorry. Thanks again!
