### ISSUE TITLE
Adopting the UKSI

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#212]
We are still thinking it would be desirable for NS to adopt the UKSI and think we may have a funding opportunity to move this forward. You provided some helpful comments a while ago on this which I incorporated into an update for trustees. I've attached this for information. I can't find a github issue about it so we may have just had an email exchange. Please could you update us on the likely time/cost and address the questions below. If you have any other thoughts then this would be useful too.

1. If we adopt the UKSI in full, how will we know when a record is submitted for a species not set up in our galleries? Maybe create a list of species with a single record and the date submitted?
2. We probably want to keep those taxon entries with made-up TVKs, ie. those not currently on the UKSI. You mentioned previously using scratchpad for this (though this doesn't mean anything to me!).
3. We currently have two drupal taxonomies - one is a species list and the other is for the gallery structure. Presumably a 'new' species would need to be added manually to these taxonomies as at present? 
4. Years ago we used to be able to upload a csv with new species details that then added the species to the taxonomy and created a species page. This was lost in the D6 upgrade but is it possible to either create something similar or simplify the set up procedure?

**Comment by davidnicholls125** [comment]
Another thought/question! At present when there is an update to the UKSI on Indicia we run the software fix that you wrote to update the drupal names/tvks. Can this be automated to it all synchs?

**Comment by johnvanbreda** [comment]
@davidnicholls125 please can you upload the comments document mentioned above. 

Some answers:
1. We could create an alert so you get an email, or a report which lists the species by first record date, so you can sort the most recent to the top.
2. What we would do is migrate all the data to UKSI where there is a direct match and then remove those taxa from your list. The remainder would be kept, which will include made-up TVKs, the + and ? taxa, and maybe some anomalies which will need to be sorted through (e.g. if there were mistakes in the TVK). I would modify the data entry tool to allow input of species on either list.
3. Correct as they define the internal menu structure and breadcrumbs. You would not have to add the species to the warehouse though.
4. Yes, we could rebuild a similar tool. I would prefer to keep this as a separate task to the UKSI switch though.

After the migration, the tool which helps keep your TVKs in sync to UKSI would still be required as now, as the same changes can happen.

**Comment by davidnicholls125** [comment]
Sorry, must have missed it earlier. Attached now.
I'm not sure that we still want to restrict the UKSI to just those species recorded in VC55 so this is probably one less task we need you to do.
[Adopting the UKSI on NatureSpot.docx](https://github.com/user-attachments/files/15775775/Adopting.the.UKSI.on.NatureSpot.docx)

**Comment by johnvanbreda** [comment]
@davidnicholls125 please can you confirm that the adoption of UKSI species group names is OK? This doesn't affect the menu structure, but would affect the following:
* When entering a species name during data entry, the group name is shown in the search results.
* On Wild Places and Parishes, the group names are shown on the Species List and Statistics tabs.
* Explore page Records tab - Taxon Group column.
* Explore page Species tab - Taxon Group column.
* Explore page Taxon Group tab.
There may be one or two other places but I think that's the main ones.

**Comment by davidnicholls125** [comment]
Thanks John - a useful reminder. I've passed this onto the other trustees for feedback. It's not a game-changer but if, for example, we maintained a simple list of species names (and TVKs perhaps) together with our gallery taxon group names, would it be possible to use these? I'm not so bothered by the Explore pages as they are little used (too slow) but the others would work better if we were able to use the same groups as on our galleries.

**Comment by johnvanbreda** [comment]
I've had a good think about the group names. There is no quick and easy fix but we can store mapping from your TVKs to group names on the server and use this to generate report outputs. We'd need to include these group names in the Elasticsearch data as well so that they are available for all types of reports. I will send you a costing separately.

Note that the Explore pages are slow because they are using the PostgreSQL database directly. We didn't switch to the much faster Elasticsearch based reporting because of the issue with group names, so if we implement the above it would make sense to switch the Explore pages over.

**Comment by davidnicholls125** [comment]
Thanks. There doesn't appear to be any strong feelings about using the iRecord group names so it doesn't need to be hurdle. One issue however is on the verification page where we have verifiers for sub-groups, such as Sawflies, which will be subsumed into Hymenoptera. I've had a look at bringing the family name into the grid but this doesn't resolve it, though perhaps a filter could be designed to include all the relevant families.....
Good news about Explore however.

**Comment by johnvanbreda** [comment]
For a filter on sawflies, you can set a search for Symphyta on the Species or other higher taxa tab of the "What" filter pane. If there are any other menu groups you are concerned about let me know - as you say it is possible to build a filter based on a list of families.

**Comment by davidnicholls125** [comment]
We have finally secured the funds to go ahead with this. Could you book this in for around mid January please?

**Comment by davidnicholls125** [comment]
Please can we firm up when this will be done? You said mid-Feb when I last raised it.....

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've started work on this. The name matching is proving to be non-trivial though. I have found there are approx. 12K taxon names in use in the NatureSpot data. I've managed to use a combination of exact and fuzzy name matching to get to the point where there are 864 names to match - some of which we expect like your aggregates and "special" species, but many of which are oddities that need to be explored and resolved. For example, your Common Pipistrelle common name is attached to the TVK for P. pipistrellus sens. lat, whereas the UKSI version is on the sensu stricto version of the taxon. 

I'll do a bit more exploration to see if there are patterns in the remaining names which can be matched automatically, but at some point I'll supply you with the remaining matches for your input as to how best to resolve them.

**Comment by johnvanbreda** [comment]
There are 818 names which I can't match automatically. Many are common names which don't exist on UKSI (or possibly synonyms). I could allow these to be matched to the currently accepted scientific name for the taxon, which would fix the vast majority. Would you like me to attach the list so you can check if there is a better way to resolve these names first?

**Comment by davidnicholls125** [comment]
Yes please.

**Comment by johnvanbreda** [comment]
Attached.

[unmatched-naturespot.csv](https://github.com/user-attachments/files/25555656/unmatched-naturespot.csv)

**Comment by davidnicholls125** [comment]
Why are we trying to match common names? Surely its the scientific names that need matching.... I've looked at a few and all have the correct scientific name and TVK as shown on NBN. (There are some entries not on NBN but a lot less than the 818.)

**Comment by johnvanbreda** [comment]
A record in Indicia contains a pointer to the name used by the recorder and that in turn has a pointer to the currently accepted name. So, we know whether a user recorded a Tawny Mining Bee or Andrena fulva for example, even though both point to the same taxonomic concept. It might be important to know, particularly when trying to investigate mistakes (for example, the common name Nettle was associated with Urtica incisa originally in UKSI, leading to lots of data entry mistakes and an apparent abundance of an unusual non-native plant. As we knew the name used by the recorder (and knew that no recorder who knew what U. incisa was would use the common name Nettle to describe it) fixing the data was simple.

We can use the accepted name match as a fall-back which was my suggestion, but that would mean that someone who had recorded a common name would end up with a record that gives the impression they had input a scientific name. It's a subtle difference that does not matter the vast majority of the time though so may be an acceptable compromise. The name would still show the current common name favoured by UKSI in the reports.

**Comment by davidnicholls125** [comment]
OK thanks. Recorders use the common name as a shortcut to bring up the species on the form. Given that all records are checked by a verifier I don't think mistaken entries is an issue as these would be spotted. We need to match the species using the scientific name. I don't understand why this would then change the record details but changing the common name entered to the scientific name isn't an issue I think.

**Comment by johnvanbreda** [comment]
Ok, thanks. I'll include a match on the remaining names just based on the external key which resolves nearly everything. There are a couple of names without TVKs (Neocrepidodera and Sphagnum rubellum) but they can be matched by hand. There are also the following names without TVKs:
* Unknown butterfly
* Unknown bee
* Unknown wasp

I can match unknown bee to Apidae but I'm less certain about Unknown wasp, is this expected to be Vespidae or a wider definition including other families and Ichneumons? Can I match unknown butterfly to Papilionoidea?

If you want to keep this looser "non-taxonomic" names in the system, then it is OK as I can simply move them to the new list of special names for NatureSpot as we need this for things like + new species anyway.

**Comment by davidnicholls125** [comment]
Great, thanks. The 'unknown bee/wasp/fungus' etc were set up to force records submitted as '? unknown' into the verification queue for the relevant taxon group - so that the specialist verifier could then review them. So they should be 'non-taxonomic'.

**Comment by johnvanbreda** [comment]
Ok I'll keep the unknown ones in your custom list. Some questions:
1. Kaliofenusa pusilla - can this map to Fenusa pusilla?
2. Do you want to keep the name 'New beetle species'?
3. Do you want to keep the name 'New - being checked'?
4. Do you want to keep the name 'Cone Gall'?
5. NatureSpot has Minettia fasciata both as agg. and sensu stricto forms. UKSI only has M. fasciata without any adornments. Can I map your 2 names to M. fasciata?
6. NatureSpot has "Coleosporium tussilaginis s. lat", UKSI has just "Coleosporium tussilaginis". Is it OK to map these?
7. Can I match "Salix alba x babylonica = Salix x sepulcralis agg." to UKSI's "Salix alba x babylonica = S. x sepulcralis"?
8. Similar to 6 - can I map "Weeping Willow agg." to UKSI's "Weeping Willow"?
9. Can I map "Bat species" to 
10. Oenanthe javanica (Java Water-dropwort) doesn't seem to be in UKSI, I presume that I should keep this on the custom list.
11. I can't find Hieracium subaequialtum on UKSI - lots of similar names, but no obvious match.

I've got approx. 40 more mismatches to resolve - will try to do these tomorrow. There are a number of names associated with unknown gall causers which I suspect you want to keep as UKSI is taxonomic so doesn't include these.

**Comment by davidnicholls125** [comment]
1. It is set up as Fenusa pusilla agg. which I don't think is set up on the UKSI (I can't see it on NBN). The page text says: The taxonomy of the sawflies feeding on Ulmus is problematic and unresolved at present. Some authors e.g. Lacourt (2020) consider all the Ulmus feeding leafminers belong to one species - Fenusa pusilla. Fenusa ulmi was recorded in Ireland (2004, Knight) as F. pusilla. In Europe there are at most two species on Elm, F. ulmi and F. altenhoferi and we have decided to treat these as F. pusilla agg. until such time as the taxonomy is resolved. We've therefore had to use an invented TVK.
2. There are several 'New....' entries and these are solely used to temporarily redet 'unknown' record submissions to relevant verifier (who wouldn't otherwise look at the 'unknown' group. It doesn't need a TVK as there aren't any accepted records (or shouldn't be!).
3.  I think we can get rid of this one.
4. Yes
5. No they aren't the same. We want both retaining.
6. No. As above - keep both.
7. No.
8.  No
9. The bat group feel there is value in having generic 'bat' records so we added this entry for them. There isn't a TVK we can use so it needs to be retained as one of the custom entries.
10. It is an escaped ornamental but has been found naturalised so yes we need to keep it as a custom entry.
11. Keep it on the custom list.

As a general point, any entries with invented TVK probably all need adding to the custom list as we will have search NBN before setting it up. It is possible that the taxon has been added to UKSI subsequently so happy to check if you send me the list.

**Comment by johnvanbreda** [comment]
I've written the script to re-organise the data but need to wait for the imminent UKSI update before going further. As well as running the script I will need to:
* Modify custom blocks which use taxon_list_id as a filter.
* Alter the master species list ID on the iform configuration.
* Check explore pages have the correct list ID.

**Comment by davidnicholls125** [comment]
A few observations:

- We've noticed that some common names that are widely used are not listed (eg Yellow Dung Fly), is there a way we can get these added?
- A lot of Sitona (genus only) records were in the pending list this morning, yet these were all verified a year or more ago.....
- Some beetle records have 'Beetles' as the group name, others have 'Insect - Coleoptera (beetles)'.... why both?

**Comment by johnvanbreda** [comment]
* Surprisingly Yellow Dung Fly isn't given as a name on UKSI, even though it's provided in the description - see https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000030409. There is a link for reporting inaccuracies at the bottom.
* I can only see one Sitona in the queue now, which is a recent record that hasn't been previously verified. Did you verify the records you saw? If you can get me an example record ID I can look at what happened in the audit trail.
* This is probably just a case of waiting for the reporting data to catch-up - the process of pumping through all the changes to Elasticsearch is only just about to complete, so although the records were now linked to UKSI the copies in the reporting system were still out of date.

**Comment by davidnicholls125** [comment]
One of our trustees has reminded me that we decided to display the full UKSI on the recording form and not just restrict this to NS species. It is on the thread above but I think we both missed this. We have had a discussion about this and feel there are pros and cons with both options but would like to try putting out the full inventory - is this OK? We do need a report or method of identifying 'new' species added (again this is mentioned above). We already have this problem with 'new' species being recorded via the app which of course has always used the full UKSI. Thanks.

**Comment by davidnicholls125** [comment]
Also, just noticed that the verification summary isn't working.....

**Comment by johnvanbreda** [comment]
The verifiers summary at https://www.naturespot.org/verifier-summary seems OK to me, apart from having a small proportion of taxa still lodged against the old group names. The reason for the ones I've checked are because they are linked to taxa that were at some point deleted, which weren't included in the migration. I've just updated approx. 60 of these where I could see an obvious match to UKSI, but the following deleted taxa still have no like-for-like mapping:
* Japanese Rose agg (could map to Japanese Rose, or move to the custom list).
* Tatianaerhynchites aequatus and as Caenorhinus aequatus.
* Goldilocks Buttercup agg. (could map to Goldilocks Buttercup, or move to the custom list).

Let me know if you want any further action on these. There are also the taxa which we have kept on the custom list, would you like me to try and match these to UKSI group names now?

I've removed the limitation on searching VC55 species now. I still need to create you a report which lists taxa that have been recorded on UKSI but are not on the VC55 list.

**Comment by davidnicholls125** [comment]
Thanks John. When I looked at the verifiers summary it only showed 18 pending records (which was clearly incorrect) but now it seems OK.
I'm not clear what you mean by deleted taxa.... All three listed are on our Indicia list, have species pages and have records. For the two plants, I see that the common names include agg but the TVK points to the ss species. I'll check with our plant expert but for now do as you suggest, map these to the ss species. I'm not sure what you need for the beetle....? (That species is set up and seems OK).
If we can now map any of the custom taxa to the UKSI then it would be helpful to do this. If you are able to do a quick check then please go ahead. I'm sure there will be quite a few that can't be mapped however.

**Comment by davidnicholls125** [comment]
The scratchpad list of custom taxa is empty..... shouldn't it include all the non-standard taxon entries without TVKs? Sue has just tried to redet a record to the 'unknown fungus' entry but nothing appeared - maybe because of the scratchpad list?
https://www.naturespot.org/scratchpad-lists/edit?scratchpad_list_id=295

**Comment by johnvanbreda** [comment]
That link is wrong - the ID of the scratchpad list for all VC55 taxa is 12403. 295 is the ID of the taxon list which contains the custom species for VC55. 

Deleted species are those which someone has clicked the Delete button on in the warehouse user interface. Japanese Rose with the agg. suffix only exists in list 8 (the old NatureSpot list) and it was deleted at some point - probably around 2017. There are 8 records which we could map to Japanese Rose but we lose the meaning of the agg in the name. 

Goldilocks Buttercup agg. is similar - it's the version of the name with agg. in it on the Indicia list 8 that has been deleted, so I can map this to Goldilocks Buttercup without the agg.

"Tatianaerhynchites aequatus and as Caenorhinus aequatus" is in the taxon list 8 as a single taxon name, which I presume is a copy and paste mistake which picked up the name and a synonym. I can map to Tatianaerhynchites aequatus.

**Comment by davidnicholls125** [comment]
I wasn't referring to 12403 but rather the 295 list for custom species (this is the link I included). This is empty.... ??

**Comment by davidnicholls125** [comment]
We've removed the 'agg' from the species page for both Japanese Rose and Goldilocks Buttercup so you can map these as proposed. Yes, the Tatianaerhynchites aequatus must be a mistake so go ahead.

**Comment by johnvanbreda** [comment]
I've tidied the records attached to these names so they are attached to the correct UKSI versions. 

2 different concepts - I understand it's confusing:

- Taxon lists are more formalised lists of taxa and we use this part of the database to hold the UKSI list (taxon_list_id=15) and the VC55 custom list (taxon_list_id=295).  
- Scratchpad lists are informal lists of items, often taxa but this isn't necessarily the case. You could for example have a scratchpad list of sites. We are using this concept to identify all the taxa recorded in VC55 in list 12403.

So, when you go to the scratchpad list ID 295, that's actually a completely different list belonging to someone else that you don't have permission to.

**Comment by davidnicholls125** [comment]
Thanks. Can you please clarify what is the correct link to the list of NatureSpot custom taxa? We have another to add. (I'm sure the 295 link came from an email you sent me recently as I copied and pasted these into our admin menu....)

**Comment by johnvanbreda** [comment]
It would be accessed via the warehouse - https://warehouse1.indicia.org.uk/index.php/taxon_list/edit/295?tab=taxa. We can set up an easier way to view these (and perhaps edit or add them) within NatureSpot if that would be useful.

**Comment by davidnicholls125** [comment]
Thanks John. This should be fine for now as there is only one or two needing access and we have the Indicia log-ins.

**Comment by davidnicholls125** [comment]
Could you put together the report telling us of the 'new' species recorded so that we can get on with setting up species pages? Typically we get around 300 per year so there is likely to be a few already in the queue. Thanks.

**Comment by johnvanbreda** [comment]
See https://www.naturespot.org/newly-added-taxa. The inclusion of Bombus terrestris is an anomaly I need to come back to.

**Comment by davidnicholls125** [comment]
There are issues with the report I've just downloaded with this link (attached). About half of the full species already have species pages set up, albeit some within the last few days. Lycogala terrestre is a long-standing page but set up as Lycogala epidendrum with L. terrestre as a synonym.
Also, is there a way of ticking off the genus or higher taxon entries so they don't keep re-appearing? As the UKSI has all the genus only entries there is likely to be a continuous flow of these but we will only want to set up pages for a select few. It is useful to see them initially but we would then want to hide them - otherwise the list will grow and grow.

[New species report 27Apr26.xlsx](https://github.com/user-attachments/files/27132923/New.species.report.27Apr26.xlsx)

**Comment by johnvanbreda** [comment]
You can hide the genera by filtering the report parameter to "Species" or "Species and Lower". Or you can add the genera to the scratchpad list which causes them to be considered included in VC55 and therefore excluded from the report.

The list shown is correct though, as its an indication of all species not on the scratchpad list and the scratchpad list was a snapshot of all your species at the point in time the UKSI update was done. It doesn't know anything about the species account pages on the Drupal site as that's within the Drupal database, not within the Indicia database, so to remove a species where you have recently added the page, you need to add the species to the scratchpad list.

**Comment by davidnicholls125** [comment]
We are still rather confused by the process....! 
The following records were submitted as 'new species' before we moved to the UKSI but we are unable to redet these records to the correct taxon (even when ticking the 'Search all species' box). How do we resolve these? 
Also, the taxa on the custom list are not appearing on the records form......

<img width="1121" height="784" alt="Image" src="https://github.com/user-attachments/assets/b062a785-cac5-4537-b035-c0e33a7e7680" />

The 'new' species we need to redet to:
Andrena wilkella
Trametes cervinia
Serpula lacrymans
Platycheirus ambiguus
Parasola misera
Heringia heringi
Amphisbatis incongruella

**Comment by davidnicholls125** [comment]
I've had a go at 'removing' taxa from the newly-added-taxa report by adding them to the sandbox list as suggested. Ichneumonidae was fine but Triturus comes up as a duplicate..... If it is already on the list why is it on the new taxa report? Also, Bombus terrestis is still listed which you noted was an anomaly and needs resolving.

<img width="209" height="51" alt="Image" src="https://github.com/user-attachments/assets/d5b6717d-54b3-4fbc-81b3-80434d624833" />

**Comment by davidnicholls125** [comment]
Sorry, closed in error! Please see the last two entries.....

**Comment by johnvanbreda** [comment]
On the verification-v2 page, if I select a + new species record, then click the re-determination "label" icon, I have to click "Search all species" to get it to work, but once I do that I can search for and select species such as Andrena wilkella. 

I've fixed the ability to search for custom species - I'd broken that when you asked me to revert to allowing a search for all species - it was allowing all UKSI, but should have been all UKSI plus all custom species.

Triturus was caused by some very early records that were determined against the wrong list - I've moved them to UKSI so this should disappear.

I'll try to look at B. terrestris shortly.

**Comment by davidnicholls125** [comment]
Thanks. I've redetted the Andrena wilkella but none of the others appear on the list. Trametes cervinia isn't on the UKSI (I'll check with Sue on this) but all the others are so I don't understand why they aren't appearing.....
Serpula lacrymans
Platycheirus ambiguus
Parasola misera
Heringia heringi
Amphisbatis incongruella

**Comment by davidnicholls125** [comment]
As well as Bombus terrestris (on the newly-added-taxa report) there are three other queries:
Andrena wilkella has been added to the scratchpad list (checked and saved) but is still displaying.....
Euphorbia amygdaloides subsp. robbiae comes up as a duplicate on the scratchpad
Acronicta tridens/psi agg. is listed but no record with this taxa seems to exist (it doesn't appear on the verification v2 page)

**Comment by davidnicholls125** [comment]
The UKSI lists sub-species and we are seeing a few records for these, eg Agrotis puta puta. As these have a different TVK these records won't appear on our species pages. Is the best solution to redet them?

**Comment by johnvanbreda** [comment]
There was a bit of legacy code still expecting to use list 8 for the species lookup which is why you couldn't find Serupula lacrymans etc, I've fixed that. 
I'll look at the other issues with the scratchpad list after I've prepped the D11 upgrade.

**Comment by johnvanbreda** [comment]
> The UKSI lists sub-species and we are seeing a few records for these, eg Agrotis puta puta. As these have a different TVK these records won't appear on our species pages. Is the best solution to redet them?

Yes, you can do. If you like I can probably work out a way to block sub-species from data entry, but you may still get the odd sub-species come through via the iRecord app route.

**Comment by davidnicholls125** [comment]
The missing species we want to redet are still not appearing.....

**Comment by johnvanbreda** [comment]
Andrena Wilkella was on the newly added taxa list because it was redetermined back onto the NatureSpot list (due to the now-fixed bug in redetermination). I've fixed the determination for you so this should shortly disappear.

The Bombus terrestris issue relates to there being a problem in iRecord's UKSI copy with 2 taxonomic concepts for the same species. I suspect that would be fixed during the UKSI update due late May, but I've remapped the 2 occurrences that had picked up the wrong copy to fix this. 

Of the remaining species to redetermine to:

- Trametes cervinia - I don't think this is on UKSI?
- Serpula lacrymans - this should appear OK.
- Platycheirus ambiguus - this should appear OK.
- Parasola misera - this should appear OK.
- Heringia heringi - this should appear OK.
- Amphisbatis incongruella - this should appear OK.
Make sure you tick the "Search all species" option.

**Comment by davidnicholls125** [comment]
Those species are still not showing..... I've just tried Platycheiris ambiguus (see below) and its not there. I did select 'search all species'

<img width="229" height="330" alt="Image" src="https://github.com/user-attachments/assets/283a0a38-5a98-4839-b6b9-c1a07fab3726" />

**Comment by johnvanbreda** [comment]
You might be getting an old copy of the JavaScript from your browser cache - try Ctrl-F5, or if that doesn't work clear the browser cache. You can see yours is still searching the old NatureSpot list as it shows the old style group name. Here's what I get:

<img width="377" height="281" alt="Image" src="https://github.com/user-attachments/assets/cbe72f91-3f89-4ef2-9bdd-e9bdd48ec8e9" />

**Comment by davidnicholls125** [comment]
Sorted! Thanks.

**Comment by johnvanbreda** [comment]
Euphorbia amygdaloides subsp. robbiae - this was the same issue as Andrena wilkella, caused by the redetermination list problem. Now fixed.

Acronicta tridens/psi agg. - the relevant record was 51987035. It showed as new for the same reason (this will hopefully stop happening now). The NatureSpot list version was showing on the newly added taxa report but the name was showing as the UKSI accepted name of Acronicta psi/tridens which explains why you couldn't find it.

I think that's all the issues explained now.

**Comment by davidnicholls125** [comment]
Another issue we've noticed is that when a 'new' species is selected on the recording form, the RAG from the previous species remains on view so it looks like the RAG relates to the new species. If there is no RAG or recording advice then the space should be empty.

**Comment by davidnicholls125** [comment]
Now we are using the UKSI, some familiar moth species are being recorded as the subspecies and others as the full species (both are listed under the same common name). Technically the subspecies is correct so we can amend the TVK to that for the relevant subspecies. However records for both need to appear on the same species page so is there a way of linking both TVKs to the same page? If not, is it possible to automatically redet full species entries to the subspecies - or hide the full species entry on the UKSI menu?


Tethea ocularis octogesimea | Figure of Eighty
Philereme transversata britannica | Dark Umber
Eupithecia intricata arceuthata | Freyer's Pug
Eupithecia icterata subfulvata | Tawny Speckled Pug
Lithophane ornitopus lactipennis | Grey Shoulder-knot
Lithophane leautieri hesperica | Blair's Shoulder-knot
Noctua interjecta caliginosa | Least Yellow Underwing
Pseudoips prasinana britannica | Green Silver-lines

**Comment by johnvanbreda** [comment]
@davidnicholls125 I suggest you keep using the species TVK on the species account page, not the sub-species. People can then record at either level (you can redetermine to the subspecies if you want for tidiness, but it won't matter for the reports). I will change the species page reports to filter on the species rather than the taxon (so a sub-species will be treated the same as a species for filtering purposes).

**Comment by johnvanbreda** [comment]
I've changed the filtering on the species page to filter by species rather than taxon. I also changed the wild place and parish species counts to count species rather than taxa.

**Comment by johnvanbreda** [comment]
> Another issue we've noticed is that when a 'new' species is selected on the recording form, the RAG from the previous species remains on view so it looks like the RAG relates to the new species. If there is no RAG or recording advice then the space should be empty.

This was an old issue, but presumably more noticeable now when doing data entry for sub-species. Now fixed. There is an issue here though in that when entering a sub-species it won't pick up the advice from the parent species account page, as the recording advice is done on a per-taxon basis and it's not easy to change. We could have a new "subspecies account" page type, which just captures the subspecies name, TVK and recording advice info, then use that for the advice. These pages would need to be excluded from the gallery/search etc.

**Comment by davidnicholls125** [comment]
Thanks. Just so I understand and can explain this to others - is it all species pages that now filter by 'species' or just those moth pages listed above? Also, what exactly do you mean by 'species rather than taxon'?

**Comment by johnvanbreda** [comment]
Yes, it applies to all species pages. It won't make any difference for species that don't have sub-species records. 

Taxon =  any level in the taxonomic hierarchy (so a species, genus, sub-species, family, kingdom etc). Species = just the species level. Before if you had a species account with the species TVK in its configuration, then the subspecies were not included in the data. As each subspecies includes 2 TVKs in its reportable data, (the taxon (subspecies) key and the parent species key) we can filter on the species key to include all the subspecies data. 

It might be clearer if I show you the keys held for _Tethea ocularis_ and _Tethea ocularis octogesimea_. First, _Tethea ocularis_:
```
taxon.accepted_taxon_id: NHMSYS0000521103
taxon.species_taxon_id: NHMSYS0000521103
```

Now _Tethea ocularis octogesimea_:
```
taxon.accepted_taxon_id: NHMSYS0021143793
taxon.species_taxon_id: NHMSYS0000521103
```

So you can see we have a choice of how we filter - to either filter on the exact taxon level using accepted_taxon_id, or species_taxon_id to filter at the species level including sub-species.

**Comment by davidnicholls125** [comment]
Thanks, that helps! What about the species pages we have for higher level taxa, eg. genus or a few at a higher level?

**Comment by johnvanbreda** [comment]
I didn't realise there were higher taxa species pages - I've made another tweak so these should be OK.

**Comment by davidnicholls125** [comment]
Thanks.
