### ISSUE TITLE
Transferring records from iRecord to NS

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#275]
As per my recent email - just logging it on github. We have received a request from the RSPB to record their VC55 data through NS and want to know if their existing iRecord data can be 'transferred'. They have emailed me a spreadsheet of verified record though there are more unverified records too which could be added to the list.

Is there a way to effectively 'transfer' selected iRecord records for VC55 into NS so that they can be viewed through our website? We could do a bulk upload of the data referred to below but this would of course duplicate them all on the iRecord database.

**Comment by johnvanbreda** [comment]
If the RSPB data was entered via the app, then there are already datasets in NatureSpot with the correct format so I can just change the website ID and survey ID on the records to match (much like the automated process which captures records added to the iRecord NatureSpot activities). 

If the RSPB data was entered via another form, then I would first need to create a dataset on NatureSpot with a matching format. This is not too tricky as there is a function which assists with cloning a dataset structure. Then as above, I just need to update the IDs. 

Send me the spreadsheet and I can do it. Or, is it a case of all records by a particular user which are inside VC55?

**Comment by davidnicholls125** [comment]
Thanks John. All the records have been submitted using an activity tag called 'Charnwood'. Could we (you!) transfer all VC55 records using this? Some records have already been verified, others haven't, but presumably the status will simply transfer as well. I'll check with the RSPB if we should go ahead on this basis.

**Comment by davidnicholls125** [comment]
They would like to go ahead with this please, transferring all VC55 records with the 'Charnwood' activity tag. As we already have a Charnwood activity set up, to avoid confusion could you set up a new activity as "Charnwood - idverde / RSPB". Would it be possible to also change the transferred records to this so that both old and new records can be viewed together?

**Comment by johnvanbreda** [comment]
Just to be certain before I do anything:
There is an activity on iRecord called "Charnwood Biodiversity Surveys". This contains 736 records all input by 1 person, mostly input via the general records forms but a few are input via the bat form.
You would like a new activity added to NatureSpot "Charnwood - idverde / RSPB".
I should move all records _if they intersect VC55_ from iRecord "Charnwood Biodiversity Surveys" to NatureSpot "Charnwood - idverde / RSPB".
In order to do this I will need to create 2 survey datasets on NatureSpot which mirror the iRecord general records and bat datasets.

Is everything above correct? Also, will any records be added to iRecord "Charnwood Biodiversity Surveys" or is this a one off?

**Comment by davidnicholls125** [comment]
That all sounds correct. My understanding is that is a one-off move and from then on all VC55 records will be submitted via NatureSpot. Thanks.

**Comment by johnvanbreda** [comment]
That's done. It will take half an hour or so to correctly ripple through the system.

**Comment by davidnicholls125** [comment]
Thanks. Could you set up the activity on the iRecord app please?

**Comment by davidnicholls125** [comment]
I can't see the activity on iRecord, please can you add this asap. Also, there are no records showing on the NS projects page for this activity, did the transferred records have the activity tag added? If not, are you able to add it?

**Comment by davidnicholls125** [comment]
Please can you look at this - we are seeing lots of poor records being submitted and need to be able to monitor all records tagged to this activity. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 FYI I'm waiting for IT Support at CEH to sort out my server access before I can look into this.

**Comment by davidnicholls125** [comment]
OK thanks. Presumably this is to set up the activity on iRecord? Does this also affect the absence of any records on the NS project page? Would any images submitted with the original iRecord submissions be transferred across to NS? I would expect so but the RSPB think that some of the records currently without images did have them.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've got server access now but I think I'm a bit confused by what is needed. I thought this was a one-off transfer of records, but you need the activity on iRecord with the app set up so that new records can be added via the app and automatically transferred? 

I notice that you've added an extra activity also called "Charnwood - idverde / RSPB" so now there are 2 under NatureSpot with the same name. It currently contains no records, so perhaps I should move this one to iRecord, configure it for use in the app, and set up the ongoing transfer so records added are moved to the NatureSpot version of the activity?

> Also, there are no records showing on the NS projects page for this activity, did the transferred records have the activity tag added? If not, are you able to add it?

The records do look like they've been correctly tagged against the activity. Which page are you expecting the records to appear on but not seeing them?

**Comment by davidnicholls125** [comment]
The transfer was a one off as they want to move over to using NS for submitting VC55 records instead of iRecord. The transfer was to ensure both past and future records could be monitored together. We agreed to use the "Charnwood - idverde / RSPB" activity tag so they could view/download the data from our project page. So all the transferred records need to have this activity tag and they will then submit all future records with this activity selected too.
There is only one 'idverde' activity tag showing on the NS projects page - https://www.naturespot.org/projects
The page where the records should appear is: https://www.naturespot.org/projects/explore?group_id=3142&implicit=f

**Comment by johnvanbreda** [comment]
Ok - the correct group was ID 2307 but it didn't have a couple of settings for it to appear correctly on NatureSpot. I've corrected this and removed the group you'd added. The correct link for the records is now https://www.naturespot.org/projects/explore?group_id=2307&implicit=f.

**Comment by davidnicholls125** [comment]
Thanks. However, when I click on the records link on the project page (same using your link above) I'm getting an elasticsearch failed error message. 
https://www.naturespot.org/projects/explore?group_id=2307&implicit=f.

**Comment by johnvanbreda** [comment]
Fixed. The filter was still associated with the iRecord group - now moved to NatureSpot.

**Comment by davidnicholls125** [comment]
Thanks. However the activity still isn't showing on iRecord. Most of their recording is done via the app so this needs to be active.

**Comment by johnvanbreda** [comment]
Sorry - I got the impression from your answer a few days ago that you didn't need the activity on iRecord. I've now added it.
