### ISSUE TITLE
'After' date

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#295]
The recording date on the species pages has suddenly starting showing as 'after' the date. Do you know why this is and can we remove it please?

![Image](https://github.com/user-attachments/assets/dc8e850d-deaf-438c-b71c-16527696ae42)

**Comment by johnvanbreda** [comment]
Fixed - a symptom of reducing the amount of data fetched from the server, I needed to add the end date field to the list of requested fields as well as the start date even though both will be the same.

**Comment by davidnicholls125** [comment]
We are still seeing 'After' on dates on the Parish and Wild Place pages.

**Comment by johnvanbreda** [comment]
Sorted, I guess I may have accidentally overwritten the change at some point when copying files.
