### ISSUE TITLE
Organise images not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#83]
It is no longer possible to move images on the Organise Images page. Also, the image captions are displaying in a separate box.
![image](https://user-images.githubusercontent.com/80914584/147814617-85daa40c-3332-4aad-a32a-32ca7d420fde.png)

**Comment by johnvanbreda** [comment]
Fixed - an issue with images that had captions breaking the HTML layout.

**Comment by davidnicholls125** [comment]
It's still the same I'm afraid....
https://www.naturespot.org.uk/ns/image-organiser?species=20443

**Comment by johnvanbreda** [comment]
Fixed. A second place in the code where the caption problem could occur - I've checked and there are no others.
